#include "mos6510.h"

// All 6502 instructions
const instruction_t instructions[256] = {
    // 0x00
    {0x00, "BRK", BRK, Implied, 1, 7, false},
    {0x01, "ORA", ORA, IndexedIndirect, 2, 6, false},
    {0x02, "JAM", NOP, Implied, 1, 2, true},
    {0x03, "SLO", SLO, IndexedIndirect, 2, 8, true},
    {0x04, "NOP", NOP, ZeroPage, 2, 3, true},
    {0x05, "ORA", ORA, ZeroPage, 2, 3, false},
    {0x06, "ASL", ASL, ZeroPage, 2, 5, false},
    {0x07, "SLO", SLO, ZeroPage, 2, 5, true},
    {0x08, "PHP", PHP, Implied, 1, 3, false},
    {0x09, "ORA", ORA, Immediate, 2, 2, false},
    {0x0A, "ASL", ASL, Accumulator, 1, 2, false},
    {0x0B, "ANC", ANC, Immediate, 2, 2, true},
    {0x0C, "NOP", NOP, Absolute, 3, 4, true},
    {0x0D, "ORA", ORA, Absolute, 3, 4, false},
    {0x0E, "ASL", ASL, Absolute, 3, 6, false},
    {0x0F, "SLO", SLO, Absolute, 3, 6, true},
    // 0x10
    {0x10, "BPL", BPL, Relative, 2, 2, false},
    {0x11, "ORA", ORA, IndirectIndexed, 2, 5, false},
    {0x12, "JAM", NOP, Implied, 1, 2, true},
    {0x13, "SLO", SLO, IndirectIndexed, 2, 8, true},
    {0x14, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x15, "ORA", ORA, ZeroPageX, 2, 4, false},
    {0x16, "ASL", ASL, ZeroPageX, 2, 6, false},
    {0x17, "SLO", SLO, ZeroPageX, 2, 6, true},
    {0x18, "CLC", CLC, Implied, 1, 2, false},
    {0x19, "ORA", ORA, AbsoluteY, 3, 4, false},
    {0x1A, "NOP", NOP, Implied, 1, 2, true},
    {0x1B, "SLO", SLO, AbsoluteY, 3, 7, true},
    {0x1C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x1D, "ORA", ORA, AbsoluteX, 3, 4, false},
    {0x1E, "ASL", ASL, AbsoluteX, 3, 7, false},
    {0x1F, "SLO", SLO, AbsoluteX, 3, 7, true},
    // 0x20
    {0x20, "JSR", JSR, Absolute, 3, 6, false},
    {0x21, "AND", AND, IndexedIndirect, 2, 6, false},
    {0x22, "JAM", NOP, Implied, 0, 2, true},
    {0x23, "RLA", RLA, IndexedIndirect, 2, 8, true},
    {0x24, "BIT", BIT, ZeroPage, 2, 3, false},
    {0x25, "AND", AND, ZeroPage, 2, 3, false},
    {0x26, "ROL", ROL, ZeroPage, 2, 5, false},
    {0x27, "RLA", RLA, ZeroPage, 2, 5, true},
    {0x28, "PLP", PLP, Implied, 1, 4, false},
    {0x29, "AND", AND, Immediate, 2, 2, false},
    {0x2A, "ROL", ROL, Accumulator, 1, 2, false},
    {0x2B, "ANC", ANC, Immediate, 2, 2, true},
    {0x2C, "BIT", BIT, Absolute, 3, 4, false},
    {0x2D, "AND", AND, Absolute, 3, 4, false},
    {0x2E, "ROL", ROL, Absolute, 3, 6, false},
    {0x2F, "RLA", RLA, Absolute, 3, 6, true},
    // 0x30
    {0x30, "BMI", BMI, Relative, 2, 2, false},
    {0x31, "AND", AND, IndirectIndexed, 2, 5, false},
    {0x32, "JAM", NOP, Implied, 0, 2, true},
    {0x33, "RLA", RLA, IndirectIndexed, 2, 8, true},
    {0x34, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x35, "AND", AND, ZeroPageX, 2, 4, false},
    {0x36, "ROL", ROL, ZeroPageX, 2, 6, false},
    {0x37, "RLA", RLA, ZeroPageX, 2, 6, true},
    {0x38, "SEC", SEC, Implied, 1, 2, false},
    {0x39, "AND", AND, AbsoluteY, 3, 4, false},
    {0x3A, "NOP", NOP, Implied, 1, 2, true},
    {0x3B, "RLA", RLA, AbsoluteY, 3, 7, true},
    {0x3C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x3D, "AND", AND, AbsoluteX, 3, 4, false},
    {0x3E, "ROL", ROL, AbsoluteX, 3, 7, false},
    {0x3F, "RLA", RLA, AbsoluteX, 3, 7, true},
    // 0x40
    {0x40, "RTI", RTI, Implied, 1, 6, false},
    {0x41, "EOR", EOR, IndexedIndirect, 2, 6, false},
    {0x42, "JAM", NOP, Implied, 0, 2, true},
    {0x43, "SRE", SRE, IndexedIndirect, 2, 8, true},
    {0x44, "NOP", NOP, ZeroPage, 2, 3, true},
    {0x45, "EOR", EOR, ZeroPage, 2, 3, false},
    {0x46, "LSR", LSR, ZeroPage, 2, 5, false},
    {0x47, "SRE", SRE, ZeroPage, 2, 5, true},
    {0x48, "PHA", PHA, Implied, 1, 3, false},
    {0x49, "EOR", EOR, Immediate, 2, 2, false},
    {0x4A, "LSR", LSR, Accumulator, 1, 2, false},
    {0x4B, "ALR", ALR, Immediate, 2, 2, true}, // 6502: ASR
    {0x4C, "JMP", JMP, Absolute, 3, 3, false},
    {0x4D, "EOR", EOR, Absolute, 3, 4, false},
    {0x4E, "LSR", LSR, Absolute, 3, 6, false},
    {0x4F, "SRE", SRE, Absolute, 3, 6, true},
    // 0x50
    {0x50, "BVC", BVC, Relative, 2, 2, false},
    {0x51, "EOR", EOR, IndirectIndexed, 2, 5, false},
    {0x52, "JAM", NOP, Implied, 0, 2, true},
    {0x53, "SRE", SRE, IndirectIndexed, 2, 8, true},
    {0x54, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x55, "EOR", EOR, ZeroPageX, 2, 4, false},
    {0x56, "LSR", LSR, ZeroPageX, 2, 6, false},
    {0x57, "SRE", SRE, ZeroPageX, 2, 6, true},
    {0x58, "CLI", CLI, Implied, 1, 2, false},
    {0x59, "EOR", EOR, AbsoluteY, 3, 4, false},
    {0x5A, "NOP", NOP, Implied, 1, 2, true},
    {0x5B, "SRE", SRE, AbsoluteY, 3, 7, true},
    {0x5C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x5D, "EOR", EOR, AbsoluteX, 3, 4, false},
    {0x5E, "LSR", LSR, AbsoluteX, 3, 7, false},
    {0x5F, "SRE", SRE, AbsoluteX, 3, 7, true},
    // 0x60
    {0x60, "RTS", RTS, Implied, 1, 6, false},
    {0x61, "ADC", ADC, IndexedIndirect, 2, 6, false},
    {0x62, "JAM", NOP, Implied, 0, 2, true},
    {0x63, "RRA", RRA, IndexedIndirect, 2, 8, true},
    {0x64, "NOP", NOP, ZeroPage, 2, 3, true},
    {0x65, "ADC", ADC, ZeroPage, 2, 3, false},
    {0x66, "ROR", ROR, ZeroPage, 2, 5, false},
    {0x67, "RRA", RRA, ZeroPage, 2, 5, true},
    {0x68, "PLA", PLA, Implied, 1, 4, false},
    {0x69, "ADC", ADC, Immediate, 2, 2, false},
    {0x6A, "ROR", ROR, Accumulator, 1, 2, false},
    {0x6B, "ARR", ARR, Immediate, 2, 2, true},
    {0x6C, "JMP", JMP, Indirect, 3, 5, false},
    {0x6D, "ADC", ADC, Absolute, 3, 4, false},
    {0x6E, "ROR", ROR, Absolute, 3, 6, false},
    {0x6F, "RRA", RRA, Absolute, 3, 6, true},
    // 0x70
    {0x70, "BVS", BVS, Relative, 2, 2, false},
    {0x71, "ADC", ADC, IndirectIndexed, 2, 5, false},
    {0x72, "JAM", NOP, Implied, 0, 2, true},
    {0x73, "RRA", RRA, IndirectIndexed, 2, 8, true},
    {0x74, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x75, "ADC", ADC, ZeroPageX, 2, 4, false},
    {0x76, "ROR", ROR, ZeroPageX, 2, 6, false},
    {0x77, "RRA", RRA, ZeroPageX, 2, 6, true},
    {0x78, "SEI", SEI, Implied, 1, 2, false},
    {0x79, "ADC", ADC, AbsoluteY, 3, 4, false},
    {0x7A, "NOP", NOP, Implied, 1, 2, true},
    {0x7B, "RRA", RRA, AbsoluteY, 3, 7, true},
    {0x7C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x7D, "ADC", ADC, AbsoluteX, 3, 4, false},
    {0x7E, "ROR", ROR, AbsoluteX, 3, 7, false},
    {0x7F, "RRA", RRA, AbsoluteX, 3, 7, true},
    // 0x80
    {0x80, "NOP", NOP, Immediate, 2, 2, true},
    {0x81, "STA", STA, IndexedIndirect, 2, 6, false},
    {0x82, "NOP", NOP, Immediate, 2, 2, true},
    {0x83, "SAX", SAX, IndexedIndirect, 2, 6, true},
    {0x84, "STY", STY, ZeroPage, 2, 3, false},
    {0x85, "STA", STA, ZeroPage, 2, 3, false},
    {0x86, "STX", STX, ZeroPage, 2, 3, false},
    {0x87, "SAX", SAX, ZeroPage, 2, 3, true},
    {0x88, "DEY", DEY, Implied, 1, 2, false},
    {0x89, "NOP", NOP, Immediate, 2, 2, true},
    {0x8A, "TXA", TXA, Implied, 1, 2, false},
    {0x8B, "ANE", XAA, Immediate, 2, 2, true}, // 6502: XAA
    {0x8C, "STY", STY, Absolute, 3, 4, false},
    {0x8D, "STA", STA, Absolute, 3, 4, false},
    {0x8E, "STX", STX, Absolute, 3, 4, false},
    {0x8F, "SAX", SAX, Absolute, 3, 4, true},
    // 0x90
    {0x90, "BCC", BCC, Relative, 2, 2, false},
    {0x91, "STA", STA, IndirectIndexed, 2, 6, false},
    {0x92, "JAM", NOP, Implied, 0, 2, true},
    {0x93, "SHA", NOP, IndirectIndexed, 2, 6, true}, // AHX
    {0x94, "STY", STY, ZeroPageX, 2, 4, false},
    {0x95, "STA", STA, ZeroPageX, 2, 4, false},
    {0x96, "STX", STX, ZeroPageY, 2, 4, false},
    {0x97, "SAX", SAX, ZeroPageY, 2, 4, true},
    {0x98, "TYA", TYA, Implied, 1, 2, false},
    {0x99, "STA", STA, AbsoluteY, 3, 5, false},
    {0x9A, "TXS", TXS, Implied, 1, 2, false},
    {0x9B, "SHS", TAS, AbsoluteY, 3, 5, true}, // TAS
    {0x9C, "SHY", NOP, AbsoluteX, 3, 5, true},
    {0x9D, "STA", STA, AbsoluteX, 3, 5, false},
    {0x9E, "SHX", NOP, AbsoluteY, 3, 5, true},
    {0x9F, "SHA", NOP, AbsoluteY, 3, 5, true}, // AHX
    // 0xA0
    {0xA0, "LDY", LDY, Immediate, 2, 2, false},
    {0xA1, "LDA", LDA, IndexedIndirect, 2, 6, false},
    {0xA2, "LDX", LDX, Immediate, 2, 2, false},
    {0xA3, "LAX", LAX, IndexedIndirect, 2, 6, true},
    {0xA4, "LDY", LDY, ZeroPage, 2, 3, false},
    {0xA5, "LDA", LDA, ZeroPage, 2, 3, false},
    {0xA6, "LDX", LDX, ZeroPage, 2, 3, false},
    {0xA7, "LAX", LAX, ZeroPage, 2, 3, true},
    {0xA8, "TAY", TAY, Implied, 1, 2, false},
    {0xA9, "LDA", LDA, Immediate, 2, 2, false},
    {0xAA, "TAX", TAX, Implied, 1, 2, false},
    {0xAB, "LAX", LAX, Immediate, 2, 2, true},
    {0xAC, "LDY", LDY, Absolute, 3, 4, false},
    {0xAD, "LDA", LDA, Absolute, 3, 4, false},
    {0xAE, "LDX", LDX, Absolute, 3, 4, false},
    {0xAF, "LAX", LAX, Absolute, 3, 4, true},
    // 0xB0
    {0xB0, "BCS", BCS, Relative, 2, 2, false},
    {0xB1, "LDA", LDA, IndirectIndexed, 2, 5, false},
    {0xB2, "JAM", NOP, Implied, 0, 2, true},
    {0xB3, "LAX", LAX, IndirectIndexed, 2, 5, true},
    {0xB4, "LDY", LDY, ZeroPageX, 2, 4, false},
    {0xB5, "LDA", LDA, ZeroPageX, 2, 4, false},
    {0xB6, "LDX", LDX, ZeroPageY, 2, 4, false},
    {0xB7, "LAX", LAX, ZeroPageY, 2, 4, true},
    {0xB8, "CLV", CLV, Implied, 1, 2, false},
    {0xB9, "LDA", LDA, AbsoluteY, 3, 4, false},
    {0xBA, "TSX", TSX, Implied, 1, 2, false},
    {0xBB, "LAS", LAS, AbsoluteY, 3, 4, true},
    {0xBC, "LDY", LDY, AbsoluteX, 3, 4, false},
    {0xBD, "LDA", LDA, AbsoluteX, 3, 4, false},
    {0xBE, "LDX", LDX, AbsoluteY, 3, 4, false},
    {0xBF, "LAX", LAX, AbsoluteY, 3, 4, true},
    // 0xC0
    {0xC0, "CPY", CPY, Immediate, 2, 2, false},
    {0xC1, "CMP", CMP, IndexedIndirect, 2, 6, false},
    {0xC2, "NOP", NOP, Immediate, 2, 2, true},
    {0xC3, "DCP", DCP, IndexedIndirect, 2, 8, true},
    {0xC4, "CPY", CPY, ZeroPage, 2, 3, false},
    {0xC5, "CMP", CMP, ZeroPage, 2, 3, false},
    {0xC6, "DEC", DEC, ZeroPage, 2, 5, false},
    {0xC7, "DCP", DCP, ZeroPage, 2, 5, true},
    {0xC8, "INY", INY, Implied, 1, 2, false},
    {0xC9, "CMP", CMP, Immediate, 2, 2, false},
    {0xCA, "DEX", DEX, Implied, 1, 2, false},
    {0xCB, "SBX", SBX, Immediate, 2, 2, true},
    {0xCC, "CPY", CPY, Absolute, 3, 4, false},
    {0xCD, "CMP", CMP, Absolute, 3, 4, false},
    {0xCE, "DEC", DEC, Absolute, 3, 6, false},
    {0xCF, "DCP", DCP, Absolute, 3, 6, true},
    // 0xD0
    {0xD0, "BNE", BNE, Relative, 2, 2, false},
    {0xD1, "CMP", CMP, IndirectIndexed, 2, 5, false},
    {0xD2, "JAM", NOP, Implied, 0, 2, true},
    {0xD3, "DCP", DCP, IndirectIndexed, 2, 8, true},
    {0xD4, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0xD5, "CMP", CMP, ZeroPageX, 2, 4, false},
    {0xD6, "DEC", DEC, ZeroPageX, 2, 6, false},
    {0xD7, "DCP", DCP, ZeroPageX, 2, 6, true},
    {0xD8, "CLD", CLD, Implied, 1, 2, false},
    {0xD9, "CMP", CMP, AbsoluteY, 3, 4, false},
    {0xDA, "NOP", NOP, Implied, 1, 2, true},
    {0xDB, "DCP", DCP, AbsoluteY, 3, 7, true},
    {0xDC, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0xDD, "CMP", CMP, AbsoluteX, 3, 4, false},
    {0xDE, "DEC", DEC, AbsoluteX, 3, 7, false},
    {0xDF, "DCP", DCP, AbsoluteX, 3, 7, true},
    // 0xE0
    {0xE0, "CPX", CPX, Immediate, 2, 2, false},
    {0xE1, "SBC", SBC, IndexedIndirect, 2, 6, false},
    {0xE2, "NOP", NOP, Immediate, 2, 2, true},
    {0xE3, "ISB", ISC, IndexedIndirect, 2, 8, true},
    {0xE4, "CPX", CPX, ZeroPage, 2, 3, false},
    {0xE5, "SBC", SBC, ZeroPage, 2, 3, false},
    {0xE6, "INC", INC, ZeroPage, 2, 5, false},
    {0xE7, "ISB", ISC, ZeroPage, 2, 5, true},
    {0xE8, "INX", INX, Implied, 1, 2, false},
    {0xE9, "SBC", SBC, Immediate, 2, 2, false},
    {0xEA, "NOP", NOP, Implied, 1, 2, false},
    {0xEB, "SBC", SBC, Immediate, 2, 2, true},
    {0xEC, "CPX", CPX, Absolute, 3, 4, false},
    {0xED, "SBC", SBC, Absolute, 3, 4, false},
    {0xEE, "INC", INC, Absolute, 3, 6, false},
    {0xEF, "ISB", ISC, Absolute, 3, 6, true},
    // 0xF0
    {0xF0, "BEQ", BEQ, Relative, 2, 2, false},
    {0xF1, "SBC", SBC, IndirectIndexed, 2, 5, false},
    {0xF2, "JAM", NOP, Implied, 0, 2, true},
    {0xF3, "ISB", ISC, IndirectIndexed, 2, 8, true},
    {0xF4, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0xF5, "SBC", SBC, ZeroPageX, 2, 4, false},
    {0xF6, "INC", INC, ZeroPageX, 2, 6, false},
    {0xF7, "ISB", ISC, ZeroPageX, 2, 6, true},
    {0xF8, "SED", SED, Implied, 1, 2, false},
    {0xF9, "SBC", SBC, AbsoluteY, 3, 4, false},
    {0xFA, "NOP", NOP, Implied, 1, 2, true},
    {0xFB, "ISB", ISC, AbsoluteY, 3, 7, true},
    {0xFC, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0xFD, "SBC", SBC, AbsoluteX, 3, 4, false},
    {0xFE, "INC", INC, AbsoluteX, 3, 7, false},
    {0xFF, "ISB", ISC, AbsoluteX, 3, 7, true},
};

// This file contains the actual opcode table definition
const opcode_t opcode_table[256] = {
    {0x00, "BRK", ADDR_IMP, 7, BRK},
    {0x01, "ORA", ADDR_INDX, 6, ORA},
    {0x02, "JAM", ADDR_IMP, 1, NOP},
    {0x03, "SLO", ADDR_INDX, 8, SLO},
    {0x04, "NOP", ADDR_ZP, 3, NOP},
    {0x05, "ORA", ADDR_ZP, 3, ORA},
    {0x06, "ASL", ADDR_ZP, 5, ASL},
    {0x07, "SLO", ADDR_ZP, 5, SLO},
    {0x08, "PHP", ADDR_IMP, 3, PHP},
    {0x09, "ORA", ADDR_IMM, 2, ORA},
    {0x0A, "ASL", ADDR_IMP, 2, ASL},
    {0x0B, "ANC", ADDR_IMM, 2, ANC},
    {0x0C, "NOP", ADDR_ABS, 4, NOP},
    {0x0D, "ORA", ADDR_ABS, 4, ORA},
    {0x0E, "ASL", ADDR_ABS, 6, ASL},
    {0x0F, "SLO", ADDR_ABS, 6, SLO},
    {0x10, "BPL", ADDR_REL, 2, BPL},
    {0x11, "ORA", ADDR_INDY, 5, ORA},
    {0x12, "JAM", ADDR_IMP, 1, NOP},
    {0x13, "SLO", ADDR_INDY, 8, SLO},
    {0x14, "NOP", ADDR_ZPX, 4, NOP},
    {0x15, "ORA", ADDR_ZPX, 4, ORA},
    {0x16, "ASL", ADDR_ZPX, 6, ASL},
    {0x17, "SLO", ADDR_ZPX, 6, SLO},
    {0x18, "CLC", ADDR_IMP, 2, CLC},
    {0x19, "ORA", ADDR_ABSY, 4, ORA},
    {0x1A, "NOP", ADDR_IMP, 2, NOP},
    {0x1B, "SLO", ADDR_ABSY, 7, SLO},
    {0x1C, "NOP", ADDR_ABSX, 4, NOP},
    {0x1D, "ORA", ADDR_ABSX, 4, ORA},
    {0x1E, "ASL", ADDR_ABSX, 7, ASL},
    {0x1F, "SLO", ADDR_ABSX, 7, SLO},
    {0x20, "JSR", ADDR_ABS, 6, JSR},
    {0x21, "AND", ADDR_INDX, 6, AND},
    {0x22, "JAM", ADDR_IMP, 1, NOP},
    {0x23, "RLA", ADDR_INDX, 8, RLA},
    {0x24, "BIT", ADDR_ZP, 3, BIT},
    {0x25, "AND", ADDR_ZP, 3, AND},
    {0x26, "ROL", ADDR_ZP, 5, ROL},
    {0x27, "RLA", ADDR_ZP, 5, RLA},
    {0x28, "PLP", ADDR_IMP, 4, PLP},
    {0x29, "AND", ADDR_IMM, 2, AND},
    {0x2A, "ROL", ADDR_IMP, 2, ROL},
    {0x2B, "ANC", ADDR_IMM, 2, ANC},
    {0x2C, "BIT", ADDR_ABS, 4, BIT},
    {0x2D, "AND", ADDR_ABS, 4, AND},
    {0x2E, "ROL", ADDR_ABS, 6, ROL},
    {0x2F, "RLA", ADDR_ABS, 6, RLA},
    {0x30, "BMI", ADDR_REL, 2, BMI},
    {0x31, "AND", ADDR_INDY, 5, AND},
    {0x32, "JAM", ADDR_IMP, 1, NOP},
    {0x33, "RLA", ADDR_INDY, 8, RLA},
    {0x34, "NOP", ADDR_ZPX, 4, NOP},
    {0x35, "AND", ADDR_ZPX, 4, AND},
    {0x36, "ROL", ADDR_ZPX, 6, ROL},
    {0x37, "RLA", ADDR_ZPX, 6, RLA},
    {0x38, "SEC", ADDR_IMP, 2, SEC},
    {0x39, "AND", ADDR_ABSY, 4, AND},
    {0x3A, "NOP", ADDR_IMP, 2, NOP},
    {0x3B, "RLA", ADDR_ABSY, 7, RLA},
    {0x3C, "NOP", ADDR_ABSX, 4, NOP},
    {0x3D, "AND", ADDR_ABSX, 4, AND},
    {0x3E, "ROL", ADDR_ABSX, 7, ROL},
    {0x3F, "RLA", ADDR_ABSX, 7, RLA},
    {0x40, "RTI", ADDR_IMP, 6, RTI},
    {0x41, "EOR", ADDR_INDX, 6, EOR},
    {0x42, "JAM", ADDR_IMP, 1, NOP},
    {0x43, "SRE", ADDR_INDX, 8, SRE},
    {0x44, "NOP", ADDR_ZP, 3, NOP},
    {0x45, "EOR", ADDR_ZP, 3, EOR},
    {0x46, "LSR", ADDR_ZP, 5, LSR},
    {0x47, "SRE", ADDR_ZP, 5, SRE},
    {0x48, "PHA", ADDR_IMP, 3, PHA},
    {0x49, "EOR", ADDR_IMM, 2, EOR},
    {0x4A, "LSR", ADDR_IMP, 2, LSR},
    {0x4B, "ALR", ADDR_IMM, 2, NOP},
    {0x4C, "JMP", ADDR_ABS, 3, JMP},
    {0x4D, "EOR", ADDR_ABS, 4, EOR},
    {0x4E, "LSR", ADDR_ABS, 6, LSR},
    {0x4F, "SRE", ADDR_ABS, 6, SRE},
    {0x50, "BVC", ADDR_REL, 2, BVC},
    {0x51, "EOR", ADDR_INDY, 5, EOR},
    {0x52, "JAM", ADDR_IMP, 1, NOP},
    {0x53, "SRE", ADDR_INDY, 8, SRE},
    {0x54, "NOP", ADDR_ZPX, 4, NOP},
    {0x55, "EOR", ADDR_ZPX, 4, EOR},
    {0x56, "LSR", ADDR_ZPX, 6, LSR},
    {0x57, "SRE", ADDR_ZPX, 6, SRE},
    {0x58, "CLI", ADDR_IMP, 2, CLI},
    {0x59, "EOR", ADDR_ABSY, 4, EOR},
    {0x5A, "NOP", ADDR_IMP, 2, NOP},
    {0x5B, "SRE", ADDR_ABSY, 7, SRE},
    {0x5C, "NOP", ADDR_ABSX, 4, NOP},
    {0x5D, "EOR", ADDR_ABSX, 4, EOR},
    {0x5E, "LSR", ADDR_ABSX, 7, LSR},
    {0x5F, "SRE", ADDR_ABSX, 7, SRE},
    {0x60, "RTS", ADDR_IMP, 6, RTS},
    {0x61, "ADC", ADDR_INDX, 6, ADC},
    {0x62, "JAM", ADDR_IMP, 1, NOP},
    {0x63, "RRA", ADDR_INDX, 8, RRA},
    {0x64, "NOP", ADDR_ZP, 3, NOP},
    {0x65, "ADC", ADDR_ZP, 3, ADC},
    {0x66, "ROR", ADDR_ZP, 5, ROR},
    {0x67, "RRA", ADDR_ZP, 5, RRA},
    {0x68, "PLA", ADDR_IMP, 4, PLA},
    {0x69, "ADC", ADDR_IMM, 2, ADC},
    {0x6A, "ROR", ADDR_IMP, 2, ROR},
    {0x6B, "ARR", ADDR_IMM, 2, ARR},
    {0x6C, "JMP", ADDR_IND, 5, JMP},
    {0x6D, "ADC", ADDR_ABS, 4, ADC},
    {0x6E, "ROR", ADDR_ABS, 6, ROR},
    {0x6F, "RRA", ADDR_ABS, 6, RRA},
    {0x70, "BVS", ADDR_REL, 2, BVS},
    {0x71, "ADC", ADDR_INDY, 5, ADC},
    {0x72, "JAM", ADDR_IMP, 1, NOP},
    {0x73, "RRA", ADDR_INDY, 8, RRA},
    {0x74, "NOP", ADDR_ZPX, 4, NOP},
    {0x75, "ADC", ADDR_ZPX, 4, ADC},
    {0x76, "ROR", ADDR_ZPX, 6, ROR},
    {0x77, "RRA", ADDR_ZPX, 6, RRA},
    {0x78, "SEI", ADDR_IMP, 2, SEI},
    {0x79, "ADC", ADDR_ABSY, 4, ADC},
    {0x7A, "NOP", ADDR_IMP, 2, NOP},
    {0x7B, "RRA", ADDR_ABSY, 7, RRA},
    {0x7C, "NOP", ADDR_ABSX, 4, NOP},
    {0x7D, "ADC", ADDR_ABSX, 4, ADC},
    {0x7E, "ROR", ADDR_ABSX, 7, ROR},
    {0x7F, "RRA", ADDR_ABSX, 7, RRA},
    {0x80, "NOP", ADDR_IMM, 2, NOP},
    {0x81, "STA", ADDR_INDX, 6, STA},
    {0x82, "NOP", ADDR_IMM, 2, NOP},
    {0x83, "SAX", ADDR_INDX, 6, SAX},
    {0x84, "STY", ADDR_ZP, 3, STY},
    {0x85, "STA", ADDR_ZP, 3, STA},
    {0x86, "STX", ADDR_ZP, 3, STX},
    {0x87, "SAX", ADDR_ZP, 3, SAX},
    {0x88, "DEY", ADDR_IMP, 2, DEY},
    {0x89, "NOP", ADDR_IMM, 2, NOP},
    {0x8A, "TXA", ADDR_IMP, 2, TXA},
    {0x8B, "XAA", ADDR_IMM, 2, XAA},
    {0x8C, "STY", ADDR_ABS, 4, STY},
    {0x8D, "STA", ADDR_ABS, 4, STA},
    {0x8E, "STX", ADDR_ABS, 4, STX},
    {0x8F, "SAX", ADDR_ABS, 4, SAX},
    {0x90, "BCC", ADDR_REL, 2, BCC},
    {0x91, "STA", ADDR_INDY, 6, STA},
    {0x92, "JAM", ADDR_IMP, 1, NOP},
    {0x93, "AHX", ADDR_INDY, 6, NOP},
    {0x94, "STY", ADDR_ZPX, 4, STY},
    {0x95, "STA", ADDR_ZPX, 4, STA},
    {0x96, "STX", ADDR_ZPY, 4, STX},
    {0x97, "SAX", ADDR_ZPY, 4, SAX},
    {0x98, "TYA", ADDR_IMP, 2, TYA},
    {0x99, "STA", ADDR_ABSY, 5, STA},
    {0x9A, "TXS", ADDR_IMP, 2, TXS},
    {0x9B, "TAS", ADDR_ABSY, 5, TAS},
    {0x9C, "SHY", ADDR_ABSX, 5, NOP},
    {0x9D, "STA", ADDR_ABSX, 5, STA},
    {0x9E, "SHX", ADDR_ABSY, 5, NOP},
    {0x9F, "AHX", ADDR_ABSY, 5, NOP},
    {0xA0, "LDY", ADDR_IMM, 2, LDY},
    {0xA1, "LDA", ADDR_INDX, 6, LDA},
    {0xA2, "LDX", ADDR_IMM, 2, LDX},
    {0xA3, "LAX", ADDR_INDX, 6, LAX},
    {0xA4, "LDY", ADDR_ZP, 3, LDY},
    {0xA5, "LDA", ADDR_ZP, 3, LDA},
    {0xA6, "LDX", ADDR_ZP, 3, LDX},
    {0xA7, "LAX", ADDR_ZP, 3, LAX},
    {0xA8, "TAY", ADDR_IMP, 2, TAY},
    {0xA9, "LDA", ADDR_IMM, 2, LDA},
    {0xAA, "TAX", ADDR_IMP, 2, TAX},
    {0xAB, "LAX", ADDR_IMM, 2, LAX},
    {0xAC, "LDY", ADDR_ABS, 4, LDY},
    {0xAD, "LDA", ADDR_ABS, 4, LDA},
    {0xAE, "LDX", ADDR_ABS, 4, LDX},
    {0xAF, "LAX", ADDR_ABS, 4, LAX},
    {0xB0, "BCS", ADDR_REL, 2, BCS},
    {0xB1, "LDA", ADDR_INDY, 5, LDA},
    {0xB2, "JAM", ADDR_IMP, 1, NOP},
    {0xB3, "LAX", ADDR_INDY, 5, LAX},
    {0xB4, "LDY", ADDR_ZPX, 4, LDY},
    {0xB5, "LDA", ADDR_ZPX, 4, LDA},
    {0xB6, "LDX", ADDR_ZPY, 4, LDX},
    {0xB7, "LAX", ADDR_ZPY, 4, LAX},
    {0xB8, "CLV", ADDR_IMP, 2, CLV},
    {0xB9, "LDA", ADDR_ABSY, 4, LDA},
    {0xBA, "TSX", ADDR_IMP, 2, TSX},
    {0xBB, "LAS", ADDR_ABSY, 4, LAS},
    {0xBC, "LDY", ADDR_ABSX, 4, LDY},
    {0xBD, "LDA", ADDR_ABSX, 4, LDA},
    {0xBE, "LDX", ADDR_ABSY, 4, LDX},
    {0xBF, "LAX", ADDR_ABSY, 4, LAX},
    {0xC0, "CPY", ADDR_IMM, 2, CPY},
    {0xC1, "CMP", ADDR_INDX, 6, CMP},
    {0xC2, "NOP", ADDR_IMM, 2, NOP},
    {0xC3, "DCP", ADDR_INDX, 8, DCP},
    {0xC4, "CPY", ADDR_ZP, 3, CPY},
    {0xC5, "CMP", ADDR_ZP, 3, CMP},
    {0xC6, "DEC", ADDR_ZP, 5, DEC},
    {0xC7, "DCP", ADDR_ZP, 5, DCP},
    {0xC8, "INY", ADDR_IMP, 2, INY},
    {0xC9, "CMP", ADDR_IMM, 2, CMP},
    {0xCA, "DEX", ADDR_IMP, 2, DEX},
    {0xCB, "SBX", ADDR_IMM, 2, SBX}, // 6502: AXS
    {0xCC, "CPY", ADDR_ABS, 4, CPY},
    {0xCD, "CMP", ADDR_ABS, 4, CMP},
    {0xCE, "DEC", ADDR_ABS, 6, DEC},
    {0xCF, "DCP", ADDR_ABS, 6, DCP},
    {0xD0, "BNE", ADDR_REL, 2, BNE},
    {0xD1, "CMP", ADDR_INDY, 5, CMP},
    {0xD2, "JAM", ADDR_IMP, 1, NOP},
    {0xD3, "DCP", ADDR_INDY, 8, DCP},
    {0xD4, "NOP", ADDR_ZPX, 4, NOP},
    {0xD5, "CMP", ADDR_ZPX, 4, CMP},
    {0xD6, "DEC", ADDR_ZPX, 6, DEC},
    {0xD7, "DCP", ADDR_ZPX, 6, DCP},
    {0xD8, "CLD", ADDR_IMP, 2, CLD},
    {0xD9, "CMP", ADDR_ABSY, 4, CMP},
    {0xDA, "NOP", ADDR_IMP, 2, NOP},
    {0xDB, "DCP", ADDR_ABSY, 7, DCP},
    {0xDC, "NOP", ADDR_ABSX, 4, NOP},
    {0xDD, "CMP", ADDR_ABSX, 4, CMP},
    {0xDE, "DEC", ADDR_ABSX, 7, DEC},
    {0xDF, "DCP", ADDR_ABSX, 7, DCP},
    {0xE0, "CPX", ADDR_IMM, 2, CPX},
    {0xE1, "SBC", ADDR_INDX, 6, SBC},
    {0xE2, "NOP", ADDR_IMM, 2, NOP},
    {0xE3, "ISC", ADDR_INDX, 8, ISC},
    {0xE4, "CPX", ADDR_ZP, 3, CPX},
    {0xE5, "SBC", ADDR_ZP, 3, SBC},
    {0xE6, "INC", ADDR_ZP, 5, INC},
    {0xE7, "ISC", ADDR_ZP, 5, ISC},
    {0xE8, "INX", ADDR_IMP, 2, INX},
    {0xE9, "SBC", ADDR_IMM, 2, SBC},
    {0xEA, "NOP", ADDR_IMP, 2, NOP},
    {0xEB, "USB", ADDR_IMM, 2, NOP},
    {0xEC, "CPX", ADDR_ABS, 4, CPX},
    {0xED, "SBC", ADDR_ABS, 4, SBC},
    {0xEE, "INC", ADDR_ABS, 6, INC},
    {0xEF, "ISC", ADDR_ABS, 6, ISC},
    {0xF0, "BEQ", ADDR_REL, 2, BEQ},
    {0xF1, "SBC", ADDR_INDY, 5, SBC},
    {0xF2, "JAM", ADDR_IMP, 1, NOP},
    {0xF3, "ISC", ADDR_INDY, 8, ISC},
    {0xF4, "NOP", ADDR_ZPX, 4, NOP},
    {0xF5, "SBC", ADDR_ZPX, 4, SBC},
    {0xF6, "INC", ADDR_ZPX, 6, INC},
    {0xF7, "ISC", ADDR_ZPX, 6, ISC},
    {0xF8, "SED", ADDR_IMP, 2, SED},
    {0xF9, "SBC", ADDR_ABSY, 4, SBC},
    {0xFA, "NOP", ADDR_IMP, 2, NOP},
    {0xFB, "ISC", ADDR_ABSY, 7, ISC},
    {0xFC, "NOP", ADDR_ABSX, 4, NOP},
    {0xFD, "SBC", ADDR_ABSX, 4, SBC},
    {0xFE, "INC", ADDR_ABSX, 7, INC},
    {0xFF, "ISC", ADDR_ABSX, 7, ISC},
};