/*
 * C64 Emulator - Instruction Table
 * 
 * Complete 256-entry opcode table for the 6502/6510.
 */

#include "cpu.h"
#include "mos6510.h"

/* The complete instruction set */
const Instruction instructions[256] = {
    /* 0x00 */
    {0x00, "BRK", BRK, Implied, 1, 7, false},
    {0x01, "ORA", ORA, IndexedIndirect, 2, 6, false},
    {0x02, "JAM", JAM, Implied, 1, 2, true},
    {0x03, "SLO", SLO, IndexedIndirect, 2, 8, true},
    {0x04, "NOP", NOP, ZeroPage, 2, 3, true},
    {0x05, "ORA", ORA, ZeroPage, 2, 3, false},
    {0x06, "ASL", ASL, ZeroPage, 2, 5, false},
    {0x07, "SLO", SLO, ZeroPage, 2, 5, true},
    {0x08, "PHP", PHP, Implied, 1, 3, false},
    {0x09, "ORA", ORA, Immediate, 2, 2, false},
    {0x0A, "ASL", ASL, Accumulator, 1, 2, false},
    {0x0B, "ANC", ANC, Immediate, 2, 2, true},
    {0x0C, "NOP", NOP, Absolute, 3, 4, true},
    {0x0D, "ORA", ORA, Absolute, 3, 4, false},
    {0x0E, "ASL", ASL, Absolute, 3, 6, false},
    {0x0F, "SLO", SLO, Absolute, 3, 6, true},

    /* 0x10 */
    {0x10, "BPL", BPL, Relative, 2, 2, false},
    {0x11, "ORA", ORA, IndirectIndexed, 2, 5, false},
    {0x12, "JAM", JAM, Implied, 1, 2, true},
    {0x13, "SLO", SLO, IndirectIndexed, 2, 8, true},
    {0x14, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x15, "ORA", ORA, ZeroPageX, 2, 4, false},
    {0x16, "ASL", ASL, ZeroPageX, 2, 6, false},
    {0x17, "SLO", SLO, ZeroPageX, 2, 6, true},
    {0x18, "CLC", CLC, Implied, 1, 2, false},
    {0x19, "ORA", ORA, AbsoluteY, 3, 4, false},
    {0x1A, "NOP", NOP, Implied, 1, 2, true},
    {0x1B, "SLO", SLO, AbsoluteY, 3, 7, true},
    {0x1C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x1D, "ORA", ORA, AbsoluteX, 3, 4, false},
    {0x1E, "ASL", ASL, AbsoluteX, 3, 7, false},
    {0x1F, "SLO", SLO, AbsoluteX, 3, 7, true},

    /* 0x20 */
    {0x20, "JSR", JSR, Absolute, 3, 6, false},
    {0x21, "AND", AND, IndexedIndirect, 2, 6, false},
    {0x22, "JAM", JAM, Implied, 1, 2, true},
    {0x23, "RLA", RLA, IndexedIndirect, 2, 8, true},
    {0x24, "BIT", BIT, ZeroPage, 2, 3, false},
    {0x25, "AND", AND, ZeroPage, 2, 3, false},
    {0x26, "ROL", ROL, ZeroPage, 2, 5, false},
    {0x27, "RLA", RLA, ZeroPage, 2, 5, true},
    {0x28, "PLP", PLP, Implied, 1, 4, false},
    {0x29, "AND", AND, Immediate, 2, 2, false},
    {0x2A, "ROL", ROL, Accumulator, 1, 2, false},
    {0x2B, "ANC", ANC, Immediate, 2, 2, true},
    {0x2C, "BIT", BIT, Absolute, 3, 4, false},
    {0x2D, "AND", AND, Absolute, 3, 4, false},
    {0x2E, "ROL", ROL, Absolute, 3, 6, false},
    {0x2F, "RLA", RLA, Absolute, 3, 6, true},

    /* 0x30 */
    {0x30, "BMI", BMI, Relative, 2, 2, false},
    {0x31, "AND", AND, IndirectIndexed, 2, 5, false},
    {0x32, "JAM", JAM, Implied, 1, 2, true},
    {0x33, "RLA", RLA, IndirectIndexed, 2, 8, true},
    {0x34, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x35, "AND", AND, ZeroPageX, 2, 4, false},
    {0x36, "ROL", ROL, ZeroPageX, 2, 6, false},
    {0x37, "RLA", RLA, ZeroPageX, 2, 6, true},
    {0x38, "SEC", SEC, Implied, 1, 2, false},
    {0x39, "AND", AND, AbsoluteY, 3, 4, false},
    {0x3A, "NOP", NOP, Implied, 1, 2, true},
    {0x3B, "RLA", RLA, AbsoluteY, 3, 7, true},
    {0x3C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x3D, "AND", AND, AbsoluteX, 3, 4, false},
    {0x3E, "ROL", ROL, AbsoluteX, 3, 7, false},
    {0x3F, "RLA", RLA, AbsoluteX, 3, 7, true},

    /* 0x40 */
    {0x40, "RTI", RTI, Implied, 1, 6, false},
    {0x41, "EOR", EOR, IndexedIndirect, 2, 6, false},
    {0x42, "JAM", JAM, Implied, 1, 2, true},
    {0x43, "SRE", SRE, IndexedIndirect, 2, 8, true},
    {0x44, "NOP", NOP, ZeroPage, 2, 3, true},
    {0x45, "EOR", EOR, ZeroPage, 2, 3, false},
    {0x46, "LSR", LSR, ZeroPage, 2, 5, false},
    {0x47, "SRE", SRE, ZeroPage, 2, 5, true},
    {0x48, "PHA", PHA, Implied, 1, 3, false},
    {0x49, "EOR", EOR, Immediate, 2, 2, false},
    {0x4A, "LSR", LSR, Accumulator, 1, 2, false},
    {0x4B, "ASR", ASR, Immediate, 2, 2, true},
    {0x4C, "JMP", JMP, Absolute, 3, 3, false},
    {0x4D, "EOR", EOR, Absolute, 3, 4, false},
    {0x4E, "LSR", LSR, Absolute, 3, 6, false},
    {0x4F, "SRE", SRE, Absolute, 3, 6, true},

    /* 0x50 */
    {0x50, "BVC", BVC, Relative, 2, 2, false},
    {0x51, "EOR", EOR, IndirectIndexed, 2, 5, false},
    {0x52, "JAM", JAM, Implied, 1, 2, true},
    {0x53, "SRE", SRE, IndirectIndexed, 2, 8, true},
    {0x54, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x55, "EOR", EOR, ZeroPageX, 2, 4, false},
    {0x56, "LSR", LSR, ZeroPageX, 2, 6, false},
    {0x57, "SRE", SRE, ZeroPageX, 2, 6, true},
    {0x58, "CLI", CLI, Implied, 1, 2, false},
    {0x59, "EOR", EOR, AbsoluteY, 3, 4, false},
    {0x5A, "NOP", NOP, Implied, 1, 2, true},
    {0x5B, "SRE", SRE, AbsoluteY, 3, 7, true},
    {0x5C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x5D, "EOR", EOR, AbsoluteX, 3, 4, false},
    {0x5E, "LSR", LSR, AbsoluteX, 3, 7, false},
    {0x5F, "SRE", SRE, AbsoluteX, 3, 7, true},

    /* 0x60 */
    {0x60, "RTS", RTS, Implied, 1, 6, false},
    {0x61, "ADC", ADC, IndexedIndirect, 2, 6, false},
    {0x62, "JAM", JAM, Implied, 1, 2, true},
    {0x63, "RRA", RRA, IndexedIndirect, 2, 8, true},
    {0x64, "NOP", NOP, ZeroPage, 2, 3, true},
    {0x65, "ADC", ADC, ZeroPage, 2, 3, false},
    {0x66, "ROR", ROR, ZeroPage, 2, 5, false},
    {0x67, "RRA", RRA, ZeroPage, 2, 5, true},
    {0x68, "PLA", PLA, Implied, 1, 4, false},
    {0x69, "ADC", ADC, Immediate, 2, 2, false},
    {0x6A, "ROR", ROR, Accumulator, 1, 2, false},
    {0x6B, "ARR", ARR, Immediate, 2, 2, true},
    {0x6C, "JMP", JMP, Indirect, 3, 5, false},
    {0x6D, "ADC", ADC, Absolute, 3, 4, false},
    {0x6E, "ROR", ROR, Absolute, 3, 6, false},
    {0x6F, "RRA", RRA, Absolute, 3, 6, true},

    /* 0x70 */
    {0x70, "BVS", BVS, Relative, 2, 2, false},
    {0x71, "ADC", ADC, IndirectIndexed, 2, 5, false},
    {0x72, "JAM", JAM, Implied, 1, 2, true},
    {0x73, "RRA", RRA, IndirectIndexed, 2, 8, true},
    {0x74, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0x75, "ADC", ADC, ZeroPageX, 2, 4, false},
    {0x76, "ROR", ROR, ZeroPageX, 2, 6, false},
    {0x77, "RRA", RRA, ZeroPageX, 2, 6, true},
    {0x78, "SEI", SEI, Implied, 1, 2, false},
    {0x79, "ADC", ADC, AbsoluteY, 3, 4, false},
    {0x7A, "NOP", NOP, Implied, 1, 2, true},
    {0x7B, "RRA", RRA, AbsoluteY, 3, 7, true},
    {0x7C, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0x7D, "ADC", ADC, AbsoluteX, 3, 4, false},
    {0x7E, "ROR", ROR, AbsoluteX, 3, 7, false},
    {0x7F, "RRA", RRA, AbsoluteX, 3, 7, true},

    /* 0x80 */
    {0x80, "NOP", NOP, Immediate, 2, 2, true},
    {0x81, "STA", STA, IndexedIndirect, 2, 6, false},
    {0x82, "NOP", NOP, Immediate, 2, 2, true},
    {0x83, "SAX", SAX, IndexedIndirect, 2, 6, true},
    {0x84, "STY", STY, ZeroPage, 2, 3, false},
    {0x85, "STA", STA, ZeroPage, 2, 3, false},
    {0x86, "STX", STX, ZeroPage, 2, 3, false},
    {0x87, "SAX", SAX, ZeroPage, 2, 3, true},
    {0x88, "DEY", DEY, Implied, 1, 2, false},
    {0x89, "NOP", NOP, Immediate, 2, 2, true},
    {0x8A, "TXA", TXA, Implied, 1, 2, false},
    {0x8B, "ANE", ANE, Immediate, 2, 2, true},
    {0x8C, "STY", STY, Absolute, 3, 4, false},
    {0x8D, "STA", STA, Absolute, 3, 4, false},
    {0x8E, "STX", STX, Absolute, 3, 4, false},
    {0x8F, "SAX", SAX, Absolute, 3, 4, true},

    /* 0x90 */
    {0x90, "BCC", BCC, Relative, 2, 2, false},
    {0x91, "STA", STA, IndirectIndexed, 2, 6, false},
    {0x92, "JAM", JAM, Implied, 1, 2, true},
    {0x93, "SHA", SHA, IndirectIndexed, 2, 6, true},
    {0x94, "STY", STY, ZeroPageX, 2, 4, false},
    {0x95, "STA", STA, ZeroPageX, 2, 4, false},
    {0x96, "STX", STX, ZeroPageY, 2, 4, false},
    {0x97, "SAX", SAX, ZeroPageY, 2, 4, true},
    {0x98, "TYA", TYA, Implied, 1, 2, false},
    {0x99, "STA", STA, AbsoluteY, 3, 5, false},
    {0x9A, "TXS", TXS, Implied, 1, 2, false},
    {0x9B, "SHS", SHS, AbsoluteY, 3, 5, true},
    {0x9C, "SHY", SHY, AbsoluteX, 3, 5, true},
    {0x9D, "STA", STA, AbsoluteX, 3, 5, false},
    {0x9E, "SHX", SHX, AbsoluteY, 3, 5, true},
    {0x9F, "SHA", SHA, AbsoluteY, 3, 5, true},

    /* 0xA0 */
    {0xA0, "LDY", LDY, Immediate, 2, 2, false},
    {0xA1, "LDA", LDA, IndexedIndirect, 2, 6, false},
    {0xA2, "LDX", LDX, Immediate, 2, 2, false},
    {0xA3, "LAX", LAX, IndexedIndirect, 2, 6, true},
    {0xA4, "LDY", LDY, ZeroPage, 2, 3, false},
    {0xA5, "LDA", LDA, ZeroPage, 2, 3, false},
    {0xA6, "LDX", LDX, ZeroPage, 2, 3, false},
    {0xA7, "LAX", LAX, ZeroPage, 2, 3, true},
    {0xA8, "TAY", TAY, Implied, 1, 2, false},
    {0xA9, "LDA", LDA, Immediate, 2, 2, false},
    {0xAA, "TAX", TAX, Implied, 1, 2, false},
    {0xAB, "LXA", LXA, Immediate, 2, 2, true},
    {0xAC, "LDY", LDY, Absolute, 3, 4, false},
    {0xAD, "LDA", LDA, Absolute, 3, 4, false},
    {0xAE, "LDX", LDX, Absolute, 3, 4, false},
    {0xAF, "LAX", LAX, Absolute, 3, 4, true},

    /* 0xB0 */
    {0xB0, "BCS", BCS, Relative, 2, 2, false},
    {0xB1, "LDA", LDA, IndirectIndexed, 2, 5, false},
    {0xB2, "JAM", JAM, Implied, 1, 2, true},
    {0xB3, "LAX", LAX, IndirectIndexed, 2, 5, true},
    {0xB4, "LDY", LDY, ZeroPageX, 2, 4, false},
    {0xB5, "LDA", LDA, ZeroPageX, 2, 4, false},
    {0xB6, "LDX", LDX, ZeroPageY, 2, 4, false},
    {0xB7, "LAX", LAX, ZeroPageY, 2, 4, true},
    {0xB8, "CLV", CLV, Implied, 1, 2, false},
    {0xB9, "LDA", LDA, AbsoluteY, 3, 4, false},
    {0xBA, "TSX", TSX, Implied, 1, 2, false},
    {0xBB, "LAS", LAS, AbsoluteY, 3, 4, true},
    {0xBC, "LDY", LDY, AbsoluteX, 3, 4, false},
    {0xBD, "LDA", LDA, AbsoluteX, 3, 4, false},
    {0xBE, "LDX", LDX, AbsoluteY, 3, 4, false},
    {0xBF, "LAX", LAX, AbsoluteY, 3, 4, true},

    /* 0xC0 */
    {0xC0, "CPY", CPY, Immediate, 2, 2, false},
    {0xC1, "CMP", CMP, IndexedIndirect, 2, 6, false},
    {0xC2, "NOP", NOP, Immediate, 2, 2, true},
    {0xC3, "DCP", DCP, IndexedIndirect, 2, 8, true},
    {0xC4, "CPY", CPY, ZeroPage, 2, 3, false},
    {0xC5, "CMP", CMP, ZeroPage, 2, 3, false},
    {0xC6, "DEC", DEC, ZeroPage, 2, 5, false},
    {0xC7, "DCP", DCP, ZeroPage, 2, 5, true},
    {0xC8, "INY", INY, Implied, 1, 2, false},
    {0xC9, "CMP", CMP, Immediate, 2, 2, false},
    {0xCA, "DEX", DEX, Implied, 1, 2, false},
    {0xCB, "SBX", SBX, Immediate, 2, 2, true},
    {0xCC, "CPY", CPY, Absolute, 3, 4, false},
    {0xCD, "CMP", CMP, Absolute, 3, 4, false},
    {0xCE, "DEC", DEC, Absolute, 3, 6, false},
    {0xCF, "DCP", DCP, Absolute, 3, 6, true},

    /* 0xD0 */
    {0xD0, "BNE", BNE, Relative, 2, 2, false},
    {0xD1, "CMP", CMP, IndirectIndexed, 2, 5, false},
    {0xD2, "JAM", JAM, Implied, 1, 2, true},
    {0xD3, "DCP", DCP, IndirectIndexed, 2, 8, true},
    {0xD4, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0xD5, "CMP", CMP, ZeroPageX, 2, 4, false},
    {0xD6, "DEC", DEC, ZeroPageX, 2, 6, false},
    {0xD7, "DCP", DCP, ZeroPageX, 2, 6, true},
    {0xD8, "CLD", CLD, Implied, 1, 2, false},
    {0xD9, "CMP", CMP, AbsoluteY, 3, 4, false},
    {0xDA, "NOP", NOP, Implied, 1, 2, true},
    {0xDB, "DCP", DCP, AbsoluteY, 3, 7, true},
    {0xDC, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0xDD, "CMP", CMP, AbsoluteX, 3, 4, false},
    {0xDE, "DEC", DEC, AbsoluteX, 3, 7, false},
    {0xDF, "DCP", DCP, AbsoluteX, 3, 7, true},

    /* 0xE0 */
    {0xE0, "CPX", CPX, Immediate, 2, 2, false},
    {0xE1, "SBC", SBC, IndexedIndirect, 2, 6, false},
    {0xE2, "NOP", NOP, Immediate, 2, 2, true},
    {0xE3, "ISB", ISB, IndexedIndirect, 2, 8, true},
    {0xE4, "CPX", CPX, ZeroPage, 2, 3, false},
    {0xE5, "SBC", SBC, ZeroPage, 2, 3, false},
    {0xE6, "INC", INC, ZeroPage, 2, 5, false},
    {0xE7, "ISB", ISB, ZeroPage, 2, 5, true},
    {0xE8, "INX", INX, Implied, 1, 2, false},
    {0xE9, "SBC", SBC, Immediate, 2, 2, false},
    {0xEA, "NOP", NOP, Implied, 1, 2, false},
    {0xEB, "SBC", SBC, Immediate, 2, 2, true},
    {0xEC, "CPX", CPX, Absolute, 3, 4, false},
    {0xED, "SBC", SBC, Absolute, 3, 4, false},
    {0xEE, "INC", INC, Absolute, 3, 6, false},
    {0xEF, "ISB", ISB, Absolute, 3, 6, true},

    /* 0xF0 */
    {0xF0, "BEQ", BEQ, Relative, 2, 2, false},
    {0xF1, "SBC", SBC, IndirectIndexed, 2, 5, false},
    {0xF2, "JAM", JAM, Implied, 1, 2, true},
    {0xF3, "ISB", ISB, IndirectIndexed, 2, 8, true},
    {0xF4, "NOP", NOP, ZeroPageX, 2, 4, true},
    {0xF5, "SBC", SBC, ZeroPageX, 2, 4, false},
    {0xF6, "INC", INC, ZeroPageX, 2, 6, false},
    {0xF7, "ISB", ISB, ZeroPageX, 2, 6, true},
    {0xF8, "SED", SED, Implied, 1, 2, false},
    {0xF9, "SBC", SBC, AbsoluteY, 3, 4, false},
    {0xFA, "NOP", NOP, Implied, 1, 2, true},
    {0xFB, "ISB", ISB, AbsoluteY, 3, 7, true},
    {0xFC, "NOP", NOP, AbsoluteX, 3, 4, true},
    {0xFD, "SBC", SBC, AbsoluteX, 3, 4, false},
    {0xFE, "INC", INC, AbsoluteX, 3, 7, false},
    {0xFF, "ISB", ISB, AbsoluteX, 3, 7, true},
};
